"""
This is to plot the heatmap of slopes for the {p, q} lattices. The slopes are precomputed and stored in a numpy array. The heatmap is generated by randomwalk.npy. The slopes are loaded from a .npy file, and the heatmap is displayed with appropriate labels and color mapping.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

FILEPATH = ""
P_MIN = 4
P_MAX = 20
Q_MIN = 4
Q_MAX = 20

slopes = np.load(FILEPATH)
plot_data = slopes[4:20, 4:20]  # Adjust indices to match the range of p and q values
# --- Plotting the Heatmap ---
plt.figure(figsize=(12, 9))

# Slice the array to remove the unused 0-3 indices for cleaner plotting
plot_data = slopes[P_MIN:P_MAX, Q_MIN:Q_MAX]

ax = plt.gca()
ax.set_facecolor('lightgray')  # shows through for NaN (failed/non-hyperbolic) cells

# Create the heatmap
ax = sns.heatmap(
    plot_data, 
    xticklabels=range(Q_MIN, Q_MAX), 
    yticklabels=range(P_MIN, P_MAX),
    cmap="magma",       # 'magma' or 'viridis' are great for scientific data
    annot=False,        # Change to True if you want the exact numbers printed in each cell
    fmt=".2f",          # Formats the annotations to 2 decimal places if annot=True
    cbar_kws={'label': 'Ballistic Velocity (Slope m)'},
    linewidths=0.5,     # Adds gridlines between cells
    ax=ax
)

# Invert Y-axis so p increases upwards (optional, but standard for cartesian grids)
ax.invert_yaxis()

plt.title("Heatmap of Quantum Walk Dispersion Slopes on {p, q} Lattices", pad=20, fontsize=14)
plt.xlabel("q (Polygons meeting at a vertex)", fontsize=12)
plt.ylabel("p (Sides per polygon)", fontsize=12)

plt.tight_layout()
plt.show()